package com.sentinelcore.backend.entity;

import java.util.Set;
import static com.sentinelcore.backend.entity.Permission.*;

public enum Role {
    SUPER_ADMIN(Set.of(
        USER_CREATE, USER_EDIT, USER_DELETE, USER_ROLE_ASSIGN, USER_PASSWORD_RESET, USER_STATUS_TOGGLE,
        ASSET_MANAGE, ALERT_MANAGE, INCIDENT_MANAGE, VULNERABILITY_MANAGE, RISK_MANAGE, PATCH_MANAGE, REPORT_MANAGE, AUDIT_LOG_VIEW, SETTINGS_MANAGE,
        ASSET_VIEW, ALERT_VIEW, INCIDENT_VIEW, VULNERABILITY_VIEW, THREAT_INTEL_VIEW, RISK_VIEW, REPORT_VIEW, PROFILE_MANAGE
    )),

    ADMIN(Set.of(
        USER_CREATE, USER_EDIT, USER_ROLE_ASSIGN, USER_STATUS_TOGGLE,
        ASSET_MANAGE, ALERT_MANAGE, INCIDENT_MANAGE, VULNERABILITY_MANAGE, REPORT_MANAGE,
        ASSET_VIEW, ALERT_VIEW, INCIDENT_VIEW, VULNERABILITY_VIEW, REPORT_VIEW, PROFILE_MANAGE
    )),

    SECURITY_ANALYST(Set.of(
        ALERT_MANAGE, INCIDENT_MANAGE,
        ASSET_VIEW, ALERT_VIEW, INCIDENT_VIEW, THREAT_INTEL_VIEW, VULNERABILITY_VIEW, REPORT_VIEW, PROFILE_MANAGE
    )),

    INCIDENT_MANAGER(Set.of(
        INCIDENT_MANAGE,
        ALERT_VIEW, INCIDENT_VIEW, REPORT_VIEW, PROFILE_MANAGE
    )),

    VULNERABILITY_MANAGER(Set.of(
        VULNERABILITY_MANAGE, RISK_MANAGE, PATCH_MANAGE,
        ASSET_VIEW, VULNERABILITY_VIEW, RISK_VIEW, PROFILE_MANAGE
    )),

    ASSET_MANAGER(Set.of(
        ASSET_MANAGE,
        ASSET_VIEW, PROFILE_MANAGE
    )),

    AUDITOR(Set.of(
        ASSET_VIEW, ALERT_VIEW, INCIDENT_VIEW, VULNERABILITY_VIEW, THREAT_INTEL_VIEW, RISK_VIEW, REPORT_VIEW, AUDIT_LOG_VIEW, PROFILE_MANAGE
    )),

    USER(Set.of(
        PROFILE_MANAGE
    ));

    private final Set<Permission> permissions;

    Role(Set<Permission> permissions) {
        this.permissions = permissions;
    }

    public Set<Permission> getPermissions() {
        return permissions;
    }
}